# Generated by Django 3.2.7 on 2022-04-19 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='対戦名')),
                ('even', models.BooleanField(verbose_name='引き分け')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='試合日時')),
            ],
            options={
                'verbose_name_plural': 'Match',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='プレイヤー')),
                ('inactive', models.BooleanField(blank=True, default=False, verbose_name='引退')),
                ('latest_rating', models.FloatField(default=0, verbose_name='最新レーティング')),
            ],
            options={
                'verbose_name_plural': 'Player',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='本文')),
                ('est_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1500.0, verbose_name='レーティング')),
                ('appr_rating', models.FloatField(default=0, verbose_name='見掛けのレーティング')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arg_match', to='duel.match', verbose_name='マッチ')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duel.player', verbose_name='プレイヤー')),
            ],
            options={
                'verbose_name_plural': 'Rating',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duel.team', verbose_name='所属'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Loser_ID', to='duel.player', verbose_name='敗者'),
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Team_ID', to='duel.team', verbose_name='チーム'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Winner_ID', to='duel.player', verbose_name='勝者'),
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_team', to='duel.team', verbose_name='チーム')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Affiliations',
            },
        ),
    ]
