# Generated by Django 3.2.7 on 2022-04-21 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duel', '0002_auto_20220420_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duel_affl_team', to='duel.team', verbose_name='チーム'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duel_affl_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
