# Generated by Django 3.2.7 on 2022-04-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duel', '0003_auto_20220422_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
    ]
