# Generated by Django 3.2.7 on 2022-04-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='have_team',
            field=models.BooleanField(blank=True, default=True, verbose_name='紐づいているチームの有無'),
            preserve_default=False,
        ),
    ]
