# Generated by Django 3.2.7 on 2022-09-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='have_duel_team',
        ),
        migrations.AddField(
            model_name='customuser',
            name='confirm_privacy_policy',
            field=models.BooleanField(blank=True, default=False, verbose_name='プライバシーポリシーへの同意'),
        ),
    ]
