# Generated by Django 3.2.7 on 2022-04-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_have_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='have_team',
            field=models.BooleanField(blank=True, default=False, verbose_name='紐づいているチームの有無'),
        ),
    ]
