# Generated by Django 3.2.7 on 2022-04-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_have_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='have_team',
        ),
        migrations.AddField(
            model_name='customuser',
            name='have_br_team',
            field=models.BooleanField(blank=True, default=False, verbose_name='紐づいているBRチームの有無'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='have_duel_team',
            field=models.BooleanField(blank=True, default=False, verbose_name='紐づいているDuelチームの有無'),
        ),
    ]
