# Generated by Django 3.2.7 on 2022-04-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220422_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='have_br_team',
        ),
        migrations.AddField(
            model_name='customuser',
            name='have_multi_team',
            field=models.BooleanField(blank=True, default=False, verbose_name='紐づいているmultiチームの有無'),
        ),
    ]
