# Generated by Django 3.2.7 on 2022-07-08 12:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even', models.BooleanField(verbose_name='引き分け')),
            ],
            options={
                'verbose_name_plural': 'Duel',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='試合名称')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='試合日時')),
            ],
            options={
                'verbose_name_plural': 'Game',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('release_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='公開日')),
                ('category', models.IntegerField(choices=[(1, 'お知らせ'), (2, '重要')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='プレイヤー')),
                ('inactive', models.BooleanField(blank=True, default=False, verbose_name='引退')),
                ('ltst_rating', models.IntegerField(default=0, verbose_name='最新レーティング')),
            ],
            options={
                'verbose_name_plural': 'Player',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='本文')),
                ('est_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='説明')),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_diff', models.FloatField(default=0.0, verbose_name='レーティング差分')),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_duel', to='multi.duel', verbose_name='マッチ')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multi.player', verbose_name='プレイヤー')),
            ],
            options={
                'verbose_name_plural': 'Rating',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi.team', verbose_name='所属'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, verbose_name='順位')),
                ('new_rating', models.FloatField(default=1500.0, verbose_name='対戦後のレーティング')),
                ('appr_rating', models.IntegerField(default=0, verbose_name='修正レーティング')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_game', to='multi.game', verbose_name='ゲーム')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_player', to='multi.player', verbose_name='player')),
            ],
            options={
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi.team', verbose_name='チーム'),
        ),
        migrations.AddField(
            model_name='duel',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_game', to='multi.game', verbose_name='対応するGame'),
        ),
        migrations.AddField(
            model_name='duel',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duel_los', to='multi.player', verbose_name='敗者'),
        ),
        migrations.AddField(
            model_name='duel',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duel_win', to='multi.player', verbose_name='勝者'),
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_affl_team', to='multi.team', verbose_name='チーム')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='br_affl_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Affiliations',
            },
        ),
    ]
