# Generated by Django 3.2.7 on 2022-07-25 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='page_id',
            field=models.TextField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5, '5文字以上です！'), django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', '英数字のみです！')], verbose_name='公開キーフレーズ'),
        ),
    ]
