# Generated by Django 3.2.7 on 2022-08-16 07:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0002_team_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_modify',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最終更新日'),
        ),
        migrations.AddField(
            model_name='game',
            name='memo',
            field=models.TextField(blank=True, verbose_name='コメント'),
        ),
        migrations.AddField(
            model_name='game',
            name='one_on_one',
            field=models.BooleanField(blank=True, default=False, verbose_name='1対1対戦'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=10000, verbose_name='プレイヤー'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='<チーム名>', max_length=50, verbose_name='チーム名'),
        ),
        migrations.AlterField(
            model_name='team',
            name='page_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5, '5文字以上で設定してください'), django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', '使用可能な文字は半角英数字のみです')], verbose_name='キーフレーズ'),
        ),
    ]
