# Generated by Django 3.2.7 on 2022-04-23 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0002_alter_affiliation_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participants',
            new_name='Participant',
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='試合日時'),
        ),
    ]
