# Generated by Django 3.2.7 on 2022-08-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0003_auto_20220816_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='one_on_one',
            field=models.BooleanField(blank=True, default=False, help_text='対戦結果登録時、初めに表示される入力方式を選択できます', verbose_name='入力方式'),
        ),
    ]
