# Generated by Django 3.2.7 on 2022-05-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0003_auto_20220423_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='appr_rating',
            field=models.IntegerField(default=0, verbose_name='修正レーティング'),
        ),
        migrations.AddField(
            model_name='participant',
            name='new_rating',
            field=models.FloatField(default=1500.0, verbose_name='対戦後のレーティング'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_game', to='multi.game', verbose_name='ゲーム'),
        ),
    ]
