# Generated by Django 3.2.7 on 2022-05-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0004_auto_20220507_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='latest_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='appr_rating',
        ),
        migrations.AlterField(
            model_name='rating',
            name='duel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_duel', to='multi.duel', verbose_name='マッチ'),
        ),
    ]
