# Generated by Django 3.2.7 on 2022-05-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0006_auto_20220507_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_player', to='multi.player', verbose_name='player'),
        ),
    ]
