# Generated by Django 3.2.7 on 2022-08-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0007_auto_20220816_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='need_to_recalc',
            field=models.BooleanField(default=False, verbose_name='要再計算'),
        ),
    ]
