# Generated by Django 3.2.7 on 2022-05-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0007_alter_participant_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ltst_rating',
            field=models.FloatField(default=0, verbose_name='最新レーティング'),
        ),
    ]
