# Generated by Django 3.2.7 on 2022-05-16 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0008_player_ltst_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('release_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='公開日')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='ltst_rating',
            field=models.IntegerField(default=0, verbose_name='最新レーティング'),
        ),
    ]
