# Generated by Django 3.2.7 on 2022-05-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0009_auto_20220517_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.IntegerField(choices=[(1, 'お知らせ'), (2, '重要')], default=1),
        ),
    ]
