# Generated by Django 3.2.7 on 2022-09-01 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multi', '0011_alter_player_ltst_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー'),
        ),
        migrations.AlterField(
            model_name='team',
            name='one_on_one',
            field=models.BooleanField(blank=True, default=False, help_text='対戦結果登録時に使用したい入力方式を選択できます', verbose_name='デフォルト入力方式'),
        ),
    ]
