# Generated by Django 3.2.7 on 2022-09-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0012_auto_20220901_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_affl_team', to='multi.team', verbose_name='チーム'),
        ),
    ]
