# Generated by Django 3.2.7 on 2022-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0014_auto_20220916_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='appr_rating',
        ),
        migrations.AddField(
            model_name='participant',
            name='appr_diff',
            field=models.FloatField(default=0.0, verbose_name='レーティング変化'),
        ),
        migrations.AddField(
            model_name='participant',
            name='new_appr',
            field=models.FloatField(default=1500.0, verbose_name='対戦後のレーティング'),
        ),
        migrations.AddField(
            model_name='participant',
            name='old_appr',
            field=models.FloatField(default=1500.0, verbose_name='対戦前のレーティング'),
        ),
    ]
