# Generated by Django 3.2.7 on 2022-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0015_auto_20220924_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='offset_term',
            field=models.IntegerField(blank=None, default=0, null=None, verbose_name='仮レーティング期間'),
        ),
    ]
